credentials:
  username: "username"
  password: "password"

urls:
  login_page: "https://driver-services.dvsa.gov.uk/login"
  booking_page: "https://driver-services.dvsa.gov.uk/book-pupil-driving-test"

booking:
  category: "car"
  instructor: "no"
  centres:
    - "London (Croydon)"
    - "Manchester (Salford)"
    - "Birmingham (South Yardley)"

notifications:
  slack_token: "xoxb-your-slack-bot-token"
  slack_channel: "#dvsa-alerts"
  twilio_sid: "your-twilio-sid"
  twilio_token: "your-twilio-token"
  twilio_number: "+14155238886" # Twilio sandbox WhatsApp number
  client_number: "+447xxxxxxxxx" # Client WhatsApp